#!/bin/bash
#
# Installs tooling for the CI environment.

set -exuo pipefail

# See: https://github.com/gohugoio/hugo/releases for latest.
HUGO_VERSION='0.140.2'
HUGO_SHA256='3e60245cd7ab7af933487a38b70d7247a716950e68f01cf2a4460712beb5de6c'
HUGO_FILE="hugo_extended_${HUGO_VERSION}_linux-arm64.deb"
BASE_URL='https://github.com/gohugoio/hugo/releases/download'

# Download file
curl -sSL -o "/tmp/${HUGO_FILE}" "${BASE_URL}/v${HUGO_VERSION}/${HUGO_FILE}"

# Verify hash
echo "${HUGO_SHA256}  /tmp/${HUGO_FILE}" | shasum -a 256 -c -

# Install
sudo dpkg -i "/tmp/${HUGO_FILE}"
