#!/bin/bash
#
# Installs tooling for the CI environment.

set -exuo pipefail

# See: https://github.com/gohugoio/hugo/releases for latest.
HUGO_VERSION='0.140.2'
HUGO_SHA256='fe765fa8ad9d43bc13e64ee27e0b45d55182b8cf298c5bca2e46cc0889e6826c'
HUGO_FILE="hugo_extended_${HUGO_VERSION}_linux-amd64.deb"
BASE_URL='https://github.com/gohugoio/hugo/releases/download'

# Download file
curl -sSL -o "/tmp/${HUGO_FILE}" "${BASE_URL}/v${HUGO_VERSION}/${HUGO_FILE}"

# Verify hash
echo "${HUGO_SHA256}  /tmp/${HUGO_FILE}" | shasum -a 256 -c -

# Install
sudo dpkg -i "/tmp/${HUGO_FILE}"
