# App Engine configuration file. Docs:
# https://cloud.google.com/appengine/docs/standard/go/config/appref#runtime_and_app_elements

runtime: go116

# Smallest auto-scaling standard instance, $0.05/hr
# https://cloud.google.com/appengine/docs/standard#instance_classes
instance_class: F1

# https://cloud.google.com/appengine/docs/standard/go/config/appref#automatic_scaling
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
  # Cap total cost
  max_instances: 3

# Default expiration for static assets. Set to a long duration, since all
# static assets are hashed.
# https://cloud.google.com/appengine/docs/standard/go/config/appref#default_expiration
default_expiration: '30d'

handlers:
  # Configure App Engine to serve any static assets.
  - url: /css
    static_dir: site/public/css
  - url: /styles
    static_dir: site/public/styles
  - url: /js
    static_dir: site/public/js
  - url: /images
    static_dir: site/public/images
  - url: /icons
    static_dir: site/public/icons
  - url: /emgithub
    static_dir: site/public/emgithub
  - url: /old
    static_dir: site/public/old

  # Use HTTPS for all requests.
  - url: /.*
    secure: always
    script: auto
