# App Engine configuration file. Docs:
# https://cloud.google.com/appengine/docs/standard/go/config/appref#runtime_and_app_elements

# https://cloud.google.com/appengine/docs/standard/lifecycle/support-schedule#go
runtime: go123

# Smallest auto-scaling standard instance, $0.05/hr
# https://cloud.google.com/appengine/docs/standard#instance_classes
instance_class: F1

# https://cloud.google.com/appengine/docs/standard/go/config/appref#automatic_scaling
automatic_scaling:
  min_idle_instances: automatic
  # Set to a low value to minimize overall costs.
  max_idle_instances: 1
  min_pending_latency: automatic
  max_pending_latency: automatic
  # Raised from the default of "10" to facilitate higher throughout on a single
  # instance. Max value is 80.
  # https://cloud.google.com/appengine/docs/standard/go/config/appref#max_concurrent_requests
  max_concurrent_requests: 40
  # Cap total cost
  max_instances: 3

# Default expiration for static assets. Set to a long duration, since all
# static assets are hashed.
# https://cloud.google.com/appengine/docs/standard/go/config/appref#default_expiration
default_expiration: '30d'

handlers:
  # Configure App Engine to serve any static assets.
  - url: /css
    static_dir: site/public/css
  - url: /styles
    static_dir: site/public/styles
  - url: /js
    static_dir: site/public/js
  - url: /images
    static_dir: site/public/images
  - url: /icons
    static_dir: site/public/icons
  - url: /emgithub
    static_dir: site/public/emgithub

  # Use HTTPS for all requests.
  - url: /.*
    secure: always
    script: auto
