#!/bin/bash

set -euo pipefail

D=$( cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P )

set -x

ENVIRONMENT="$("$D/environment")"

# Build the site
hugo \
    --environment="$ENVIRONMENT"

# Record the build date, because App Engine does not:
# https://issuetracker.google.com/issues/168399701
BUILD_DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
echo "$BUILD_DATE" > app/public/BUILD_DATE
