#!/bin/bash

set -e

# This assumes the built-in CircleCI environment variables:
# https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables

BASE_URL="https://api.github.com/repos/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME"

# Helper to create the "Status" object
# https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#create-a-commit-status
update_status() {
  STATUS="$(jq -n \
    --arg state "$1" \
    --arg description "$2" \
    --arg target_url "$3" \
    --arg context "$4" \
    '{
      state: $state,
      target_url: $target_url,
      description: $description,
      context: $context
    }' )"
  echo "Setting Commit Status: $STATUS"
  curl -f \
    -u "$CIRCLE_PROJECT_USERNAME:$GITHUB_TOKEN" \
    -X POST \
    -H "Accept: application/vnd.github.v3+json" \
    "$BASE_URL/statuses/$CIRCLE_SHA1" \
    -d "$STATUS"
}

# Update GitHub status to mark a pending deployment.
update_status \
  "pending" \
  "Deploying to Google App Engine..." \
  "$CIRCLE_BUILD_URL" \
  "deploy: appengine"

VERSION="$(./scripts/version)"

# Deploy to Google App Engine
set -x
gcloud app deploy app/app.yaml \
    --quiet \
    --no-promote \
    --version "$VERSION"
set +x

# Retrieve the latest version URL from the deployment.
VERSION_URL="$(gcloud app versions describe "$VERSION" \
    --service default \
    --format 'value(versionUrl)')"

# Update GitHub status to mark a successful deployment.
update_status \
  "success" \
  "Deployed to Google App Engine!" \
  "$VERSION_URL" \
  "deploy: appengine"
