#!/bin/bash

DATE="$(date '+%Y%m%dt%H%M%S')"

GIT_HASH="$(git rev-parse --short HEAD)"

NAME=''
if [[ -n "$CIRCLE_BUILD_NUM" ]]; then
    NAME="ci-${CIRCLE_BUILD_NUM}"
else
    NAME="$(git branch --show-current)"
fi

# NOTE: The rules for version validation (from CLI output) state:
#
#     May only contain lowercase letters, digits, and hyphens. Must begin and
#     end with a letter or digit. Must not exceed 63 characters.

echo "$NAME-$GIT_HASH-$DATE"
